PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbo: <http://dbpedia.org/ontology/>
SELECT *
WHERE
{{
 <{0}> dbo:populationTotal ?numberOfInhabitants .
 <{0}> rdfs:label ?cityLabel .
 filter(LANG(?cityLabel) = "en") .
}}