version: '2'
services:
  backend:
    restart: unless-stopped
    image: nuance-core:latest
    container_name: nuance-core-backend
    environment:
      - SERVICE_TYPE=backend
    ports:
      - '5050:5050'
    network_mode: host
